# -*- coding: utf-8 -*-
"""AI AGENT PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLyKmjn8h7B9TbzR7Cl3ClSG7hWVzgPI
"""

# Run this cell to print all active model IDs
models = client.models.list()
for model in models.data:
    print(model.id)

!pip -q install groq

from groq import Groq
from google.colab import userdata

# Retrieve key safely from Colab Secrets
GROQ_API_KEY = userdata.get("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY)

def ask_groq(prompt):
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=600
    )
    return response.choices[0].message.content

print("✅ Groq connected successfully!")

import datetime

# Shared Memory for storing intermediate agent outputs
memory = {
    "business_problem": "",
    "business_analysis": "",
    "market_research": "",
    "benchmarking": "",
    "financial_analysis": "",
    "strategy": "",
    "final_report": ""
}

def memory_tool(key, value):
    memory[key] = value
    return f"Memory updated: {key}"

def calculator_tool(expression):
    try:
        return eval(expression, {"__builtins__": {}})
    except Exception as e:
        return f"Calculation error: {e}"

def market_data_tool(industry):
    return {
        "industry": industry,
        "market_status": "Growing",
        "competition": "High",
        "customer_demand": "Increasing",
        "digital_adoption": "Increasing",
        "major_trend": "AI and digital transformation"
    }

def competitor_tool(company, competitors):
    return {
        "company": company,
        "competitors": competitors,
        "comparison_areas": [
            "Pricing", "Product quality", "Customer experience",
            "Technology", "Marketing", "Market reach"
        ]
    }

def report_tool(report_text, filename="AI_Management_Consultant_Report.txt"):
    with open(filename, "w", encoding="utf-8") as file:
        file.write(report_text)
    return filename

print("✅ Shared memory & tools ready!")

# Agent 1: Business Analyst
def business_analyst_agent(problem):
    prompt = f"""
    You are the Business Analyst Agent in a multi-agent AI Management Consulting system.
    Business Problem: {problem}

    Analyze the problem and provide:
    1. Business Context
    2. Stakeholders
    3. Problem Statement
    4. Business Objectives
    5. Key Challenges
    6. Important Assumptions
    """
    result = ask_groq(prompt)
    memory_tool("business_analysis", result)
    return result

# Agent 2: Market Research
def market_research_agent(problem):
    market_data = market_data_tool("Food Delivery / Technology")
    prompt = f"""
    You are the Market Research Agent.
    Business Problem: {problem}
    Available Market Data: {market_data}

    Analyze:
    1. Market condition
    2. Customer demand
    3. Industry trends
    4. Competition
    5. Growth opportunities
    6. Market threats
    """
    result = ask_groq(prompt)
    memory_tool("market_research", result)
    return result

# Agent 3: Benchmarking Agent
def benchmarking_agent(problem):
    competitor_data = competitor_tool("Target Company", ["Competitor A", "Competitor B", "Competitor C"])
    prompt = f"""
    You are the Benchmarking Agent.
    Business Problem: {problem}
    Competitor Data: {competitor_data}

    Perform a competitor benchmarking analysis covering:
    1. Products/services, 2. Pricing, 3. Customer experience,
    4. Technology, 5. Marketing, 6. Strengths & Weaknesses.
    Provide practical recommendations.
    """
    result = ask_groq(prompt)
    memory_tool("benchmarking", result)
    return result

# Agent 4: Financial Analysis Agent
def financial_analysis_agent(problem):
    prompt = f"""
    You are the Financial Analysis Agent.
    Business Problem: {problem}

    Analyze:
    1. Major cost areas
    2. Revenue opportunities
    3. Profitability considerations
    4. Financial risks
    5. Cost-saving strategies
    6. Key financial KPIs
    """
    result = ask_groq(prompt)
    memory_tool("financial_analysis", result)
    return result

# Agent 5: Strategy Advisor
def strategy_advisor_agent():
    prompt = f"""
    You are the Strategy Advisor Agent.
    Review the analysis from previous agents:
    - Business Analysis: {memory['business_analysis']}
    - Market Research: {memory['market_research']}
    - Benchmarking: {memory['benchmarking']}
    - Financial Analysis: {memory['financial_analysis']}

    Create strategic recommendations including:
    1. Main strategic problem
    2. Recommended strategy
    3. Action Plan (Short-term, Medium-term, Long-term)
    4. Expected benefits & Risks
    5. KPIs & Implementation priorities
    """
    result = ask_groq(prompt)
    memory_tool("strategy", result)
    return result

# Agent 6: Report Writer
def report_writer_agent():
    prompt = f"""
    You are the final Report Writer Agent.
    Synthesize all prior agent outputs:
    - Business Analysis: {memory['business_analysis']}
    - Market Research: {memory['market_research']}
    - Benchmarking: {memory['benchmarking']}
    - Financial Analysis: {memory['financial_analysis']}
    - Strategy: {memory['strategy']}

    Generate a comprehensive management consulting report containing:
    1. Executive Summary
    2. Business Problem & Analysis
    3. Market Analysis & Benchmarking
    4. Financial Considerations
    5. Strategic Recommendations
    6. Risk Analysis & Implementation Roadmap
    7. KPIs & Conclusion
    """
    return ask_groq(prompt)

print("✅ All 6 Agents registered!")

# MULTI AGENT WORKFLOW WITH DYNAMIC INPUT

def run_consulting_project(problem):
    print("=" * 70)
    print("        AI MANAGEMENT CONSULTANT MULTI-AGENT WORKFLOW")
    print("=" * 70)

    memory["business_problem"] = problem

    print("\n🤖 Agent 1: Business Analyst Working...")
    business_analyst_agent(problem)
    print("✅ Completed")

    print("\n🤖 Agent 2: Market Research Working...")
    market_research_agent(problem)
    print("✅ Completed")

    print("\n🤖 Agent 3: Benchmarking Working...")
    benchmarking_agent(problem)
    print("✅ Completed")

    print("\n🤖 Agent 4: Financial Analysis Working...")
    financial_analysis_agent(problem)
    print("✅ Completed")

    print("\n🤖 Agent 5: Strategy Advisor Working...")
    strategy_advisor_agent()
    print("✅ Completed")

    print("\n🤖 Agent 6: Report Writer Working...")
    final_report = report_writer_agent()
    print("✅ Completed")

    print("\n" + "=" * 70)
    print("        ALL AGENTS COMPLETED SUCCESSFULLY")
    print("=" * 70)

    return final_report

# Take input interactively from user
print("Enter your business problem (press Enter when done):")
user_problem = input("> ")

if user_problem.strip():
    final_report = run_consulting_project(user_problem)
else:
    print("⚠️ No problem entered. Please enter a valid problem.")

from google.colab import files

print("\n" + "=" * 70)
print("             HUMAN APPROVAL GATE")
print("=" * 70)

# Display report preview
print(final_report)

approval = input("\nDo you approve the recommendations? (yes/no): ")

if approval.lower() == "yes":
    filename = report_tool(final_report)
    print(f"\n✅ Report saved as: {filename}")
    files.download(filename)
else:
    print("\n❌ Recommendations rejected. Requires human revision.")

